version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hogwarts-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: hogwarts
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
